apiVersion: v1
kind: Service
metadata:
  name: my-react-app
spec:
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: worasit501/react-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

  selector:
    matchLabels:
      app: myapp
